### PR TITLE
Add support for ISBNs starting with 979

### LINKED ISSUE #7: Recent ISBN is not properly hyphenated
If have this recent french EAN : `9791091146135` that should converts, with hyphens, to : `979-10-91146-13-5`, but :

``` javascript
ISBN.parse(9791091146135).asIsbn13(true)
```

gives me `979-1-09-114613-5`

It think the problem may be that the new french prefix 979-10 is missing or that the lib may not handle recent 979- ISBNs at all.

### PR DESCRIPTION
**Pull request by clemlatz**
On second thought, I rewrote the `mkgroups.pl` file from scratch in JavaScript. I felt using the same language would add consistency to the repository and be more maintainable in the future.

I added a npm script, so next time a group updated is needed, it can be done by running:

`$ npm run get-groups`

The result will be saved in a `groups.js` file in the current directory that can be incorporated in the main file.

I also updated the `isbn.js` file to handle 979-\* isbn groups.

Fixes #7.

### CODE REVIEW

**Comment by tadas-s** [comment]
Many thanks @iwazaru ! It might take couple days though until I get a chance to review it properly, hope it's OK.

**Comment by tadas-s** [comment]
npm release will follow soon when I fix one small issue: https://travis-ci.org/tadas-s/isbnjs/jobs/115838477 . As far as I understand 979 ISBNs cannot be mapped to ISBN10 and that method should probably return `null` instead of `undefined` to be consistent with the rest of APIs.

**Comment by clemlatz** [comment]
Yes, FYI, all ISBNs issued since 2007 (including 979-prefixed ISBNs introduced in 2011) are supposed to be 13 chars long and not supposed to be translatable to the 10-chars form, although it's still mathematically possible.

**Comment by tadas-s** [comment]
@iwazaru your fix is now released, thanks for contributing!

https://www.npmjs.com/package/isbn2

**Pull request merged**
